version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app/server:/var/server
      - ./docker/volumes/logs:/var/log/nginx
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/server
    command: bash -c "cp -R /var/composer/vendor /var/server |& php-fpm"
    volumes:
      - ./app/server:/var/server
    links:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - ./docker/volumes/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8081:8080